/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publickeyinfrastructure;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import sun.security.x509.X500Name;

/**
 *
 * @author somil
 */
public class CertifyingAuthorityInterface extends javax.swing.JFrame {
    /**
     * Creates new form CertifyingAuthority
     */
    private CertifyingAuthority controller;
    

   

    public CertifyingAuthorityInterface(X500Name name) {

        initComponents();
        //setting interface
        Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
        int jFrameh=this.getSize().height;
        int jFramew=this.getSize().width;
        setLocation((dim.width-jFramew)/2,(dim.height-jFrameh)/2);  
      //issuername area
        StyledDocument doc =jIssuerNameArea.getStyledDocument();
SimpleAttributeSet center = new SimpleAttributeSet();
StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
doc.setParagraphAttributes(0, doc.getLength(), center, false);
        jIssuerNameArea.setText(CertifyingAuthority.DisplayName(name)); 
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jSettings = new javax.swing.JPanel();
        jCAIPLabel = new javax.swing.JLabel();
        jDestinationField = new javax.swing.JTextField();
        jDestinationButton = new javax.swing.JButton();
        jDestinationLabel = new javax.swing.JLabel();
        jCAIPfield = new javax.swing.JTextField();
        jBufferField = new javax.swing.JTextField();
        jApplyButton = new javax.swing.JButton();
        jCancelChangesButton = new javax.swing.JButton();
        jConnectionsLabel6 = new javax.swing.JLabel();
        jProxyLabel5 = new javax.swing.JLabel();
        jConnectionsLabel9 = new javax.swing.JLabel();
        jClearChangesButton = new javax.swing.JButton();
        jChangesSuccessfulLabel = new javax.swing.JLabel();
        jConnectionsLabel7 = new javax.swing.JLabel();
        jAlgoBox = new javax.swing.JComboBox();
        jUserName = new javax.swing.JLabel();
        jMyUNameField = new javax.swing.JTextField();
        jUserName1 = new javax.swing.JLabel();
        jCANameField = new javax.swing.JTextField();
        jSenderTable1 = new javax.swing.JPanel();
        jFileLabel = new javax.swing.JLabel();
        jRegisterButton = new javax.swing.JButton();
        jEmailIdField = new javax.swing.JTextField();
        jFileLabel1 = new javax.swing.JLabel();
        jFileLabel2 = new javax.swing.JLabel();
        jStateField = new javax.swing.JTextField();
        jFileLabel3 = new javax.swing.JLabel();
        jFileLabel4 = new javax.swing.JLabel();
        jCityField = new javax.swing.JTextField();
        jFileLabel6 = new javax.swing.JLabel();
        jNameField = new javax.swing.JTextField();
        jFileLabel9 = new javax.swing.JLabel();
        jFileLabel10 = new javax.swing.JLabel();
        jFileLabel11 = new javax.swing.JLabel();
        jFileLabel12 = new javax.swing.JLabel();
        jOUField = new javax.swing.JTextField();
        jFileLabel13 = new javax.swing.JLabel();
        jOField = new javax.swing.JTextField();
        jCountryComboBox = new javax.swing.JComboBox();
        jFileLabel14 = new javax.swing.JLabel();
        jTypeField = new javax.swing.JTextField();
        jInterLabel = new javax.swing.JLabel();
        jNumberInterCAField = new javax.swing.JTextField();
        jFileLabel15 = new javax.swing.JLabel();
        jValiditySpinner = new javax.swing.JSpinner();
        jFileLabel16 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jFileLabel17 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jFileLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jIssuerNameArea = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(96, 131, 230));
        setForeground(new java.awt.Color(154, 194, 217));

        jTabbedPane2.setBackground(new java.awt.Color(176, 224, 222));
        jTabbedPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jTabbedPane2.setForeground(new java.awt.Color(58, 152, 233));
        jTabbedPane2.setToolTipText("DOWNLOAD MANAGER");
        jTabbedPane2.setDoubleBuffered(true);
        jTabbedPane2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        jSettings.setBackground(new java.awt.Color(217, 230, 241));
        jSettings.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSettings.setForeground(new java.awt.Color(67, 254, 242));
        jSettings.setAutoscrolls(true);
        jSettings.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        jSettings.setPreferredSize(new java.awt.Dimension(1313, 2500));

        jCAIPLabel.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jCAIPLabel.setForeground(new java.awt.Color(24, 0, 161));
        jCAIPLabel.setText("Certifying Authority Address/Hostname:");
        jCAIPLabel.setFocusable(false);
        jCAIPLabel.setRequestFocusEnabled(false);

        jDestinationField.setEditable(false);
        jDestinationField.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jDestinationField.setFocusable(false);
        jDestinationField.setRequestFocusEnabled(false);

        jDestinationButton.setBackground(new java.awt.Color(15, 25, 50));
        jDestinationButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jDestinationButton.setForeground(new java.awt.Color(244, 236, 236));
        jDestinationButton.setText("Choose Folder...");
        jDestinationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDestinationButtonActionPerformed(evt);
            }
        });

        jDestinationLabel.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jDestinationLabel.setForeground(new java.awt.Color(24, 0, 161));
        jDestinationLabel.setText("Destination folder for received files");
        jDestinationLabel.setFocusable(false);
        jDestinationLabel.setRequestFocusEnabled(false);

        jCAIPfield.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jCAIPfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCAIPfieldFocusLost(evt);
            }
        });

        jBufferField.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jBufferField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jBufferFieldFocusLost(evt);
            }
        });

        jApplyButton.setBackground(new java.awt.Color(185, 164, 216));
        jApplyButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jApplyButton.setText("Apply Changes");
        jApplyButton.setActionCommand("jDownloadButton");
        jApplyButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApplyButtonActionPerformed(evt);
            }
        });

        jCancelChangesButton.setBackground(new java.awt.Color(185, 164, 216));
        jCancelChangesButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jCancelChangesButton.setText("Cancel Changes");
        jCancelChangesButton.setActionCommand("jDownloadButton");
        jCancelChangesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCancelChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelChangesButtonActionPerformed(evt);
            }
        });

        jConnectionsLabel6.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jConnectionsLabel6.setForeground(new java.awt.Color(24, 0, 161));
        jConnectionsLabel6.setText("Buffer Size");
        jConnectionsLabel6.setFocusable(false);
        jConnectionsLabel6.setRequestFocusEnabled(false);

        jProxyLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jProxyLabel5.setForeground(new java.awt.Color(161, 17, 0));
        jProxyLabel5.setText("IPv6 not supported");
        jProxyLabel5.setFocusable(false);
        jProxyLabel5.setRequestFocusEnabled(false);

        jConnectionsLabel9.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jConnectionsLabel9.setForeground(new java.awt.Color(161, 17, 0));
        jConnectionsLabel9.setText("in KB, Recommended: <10 KB");
        jConnectionsLabel9.setFocusable(false);
        jConnectionsLabel9.setRequestFocusEnabled(false);

        jClearChangesButton.setBackground(new java.awt.Color(185, 164, 216));
        jClearChangesButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jClearChangesButton.setText("Clear Changes");
        jClearChangesButton.setActionCommand("jDownloadButton");
        jClearChangesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jClearChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearChangesButtonActionPerformed(evt);
            }
        });

        jChangesSuccessfulLabel.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jChangesSuccessfulLabel.setForeground(new java.awt.Color(8, 8, 8));
        jChangesSuccessfulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jChangesSuccessfulLabel.setText("Changes Applied Successfully");
        jChangesSuccessfulLabel.setFocusable(false);

        jConnectionsLabel7.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jConnectionsLabel7.setForeground(new java.awt.Color(24, 0, 161));
        jConnectionsLabel7.setText("Type of Data Encryption Algo");
        jConnectionsLabel7.setFocusable(false);
        jConnectionsLabel7.setRequestFocusEnabled(false);

        jAlgoBox.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jAlgoBox.setMaximumRowCount(2);
        jAlgoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Advanced Encryption Standard(AES)", "Data Encrytion Standard(DES)" }));

        jUserName.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jUserName.setForeground(new java.awt.Color(251, 0, 6));
        jUserName.setText("Our UserName(as registered with Certifying Authority) ");
        jUserName.setFocusable(false);
        jUserName.setRequestFocusEnabled(false);

        jMyUNameField.setEditable(false);
        jMyUNameField.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jMyUNameField.setFocusable(false);

        jUserName1.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jUserName1.setForeground(new java.awt.Color(251, 0, 6));
        jUserName1.setText("Name of the Certified Authority(as issued in certificates)");
        jUserName1.setFocusable(false);
        jUserName1.setRequestFocusEnabled(false);

        jCANameField.setEditable(false);
        jCANameField.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jCANameField.setFocusable(false);

        javax.swing.GroupLayout jSettingsLayout = new javax.swing.GroupLayout(jSettings);
        jSettings.setLayout(jSettingsLayout);
        jSettingsLayout.setHorizontalGroup(
            jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSettingsLayout.createSequentialGroup()
                .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jSettingsLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jConnectionsLabel7)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSettingsLayout.createSequentialGroup()
                                    .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jSettingsLayout.createSequentialGroup()
                                                .addComponent(jCAIPLabel)
                                                .addGap(102, 102, 102)
                                                .addComponent(jProxyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jSettingsLayout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(jConnectionsLabel6)
                                                .addGap(244, 244, 244)
                                                .addComponent(jConnectionsLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jUserName)
                                        .addComponent(jUserName1))
                                    .addGap(40, 40, 40)
                                    .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jMyUNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jSettingsLayout.createSequentialGroup()
                                                .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jCAIPfield, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jBufferField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14))
                                            .addComponent(jAlgoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jCANameField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jSettingsLayout.createSequentialGroup()
                                    .addComponent(jClearChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(148, 148, 148)
                                    .addComponent(jCancelChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(187, 187, 187)
                                    .addComponent(jApplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSettingsLayout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jDestinationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jSettingsLayout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(jDestinationLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDestinationField, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jSettingsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jChangesSuccessfulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jSettingsLayout.setVerticalGroup(
            jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSettingsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jChangesSuccessfulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDestinationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDestinationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jDestinationButton)
                .addGap(30, 30, 30)
                .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCAIPfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCAIPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProxyLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConnectionsLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConnectionsLabel9)
                    .addComponent(jBufferField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConnectionsLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAlgoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMyUNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCANameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClearChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCancelChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jApplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1368, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Settings", jSettings);

        jSenderTable1.setBackground(new java.awt.Color(217, 230, 241));
        jSenderTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSenderTable1.setForeground(new java.awt.Color(67, 254, 242));
        jSenderTable1.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N

        jFileLabel.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jFileLabel.setForeground(new java.awt.Color(24, 0, 161));
        jFileLabel.setText("Common Name(CN): *");
        jFileLabel.setFocusable(false);
        jFileLabel.setRequestFocusEnabled(false);

        jRegisterButton.setBackground(new java.awt.Color(185, 164, 216));
        jRegisterButton.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jRegisterButton.setText("Register");
        jRegisterButton.setActionCommand("jDownloadButton");
        jRegisterButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterButtonActionPerformed(evt);
            }
        });

        jFileLabel1.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jFileLabel1.setForeground(new java.awt.Color(24, 0, 161));
        jFileLabel1.setText("Email ID (EMAILADDRESS): *");
        jFileLabel1.setFocusable(false);
        jFileLabel1.setRequestFocusEnabled(false);

        jFileLabel2.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jFileLabel2.setForeground(new java.awt.Color(24, 0, 161));
        jFileLabel2.setText("Country(C): *");
        jFileLabel2.setFocusable(false);
        jFileLabel2.setRequestFocusEnabled(false);

        jFileLabel3.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jFileLabel3.setForeground(new java.awt.Color(24, 0, 161));
        jFileLabel3.setText("State/Province(ST):");
        jFileLabel3.setFocusable(false);
        jFileLabel3.setRequestFocusEnabled(false);

        jFileLabel4.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jFileLabel4.setForeground(new java.awt.Color(24, 0, 161));
        jFileLabel4.setText("Locality (L) :");
        jFileLabel4.setFocusable(false);
        jFileLabel4.setRequestFocusEnabled(false);

        jFileLabel6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jFileLabel6.setForeground(new java.awt.Color(233, 23, 26));
        jFileLabel6.setText("REGISTRATION FORM");
        jFileLabel6.setFocusable(false);
        jFileLabel6.setRequestFocusEnabled(false);

        jFileLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jFileLabel9.setForeground(new java.awt.Color(18, 9, 64));
        jFileLabel9.setText("Subject Name Details: ");
        jFileLabel9.setFocusable(false);
        jFileLabel9.setRequestFocusEnabled(false);

        jFileLabel10.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jFileLabel10.setForeground(new java.awt.Color(17, 13, 34));
        jFileLabel10.setText("To be filled for registration if you wish to be of type:   ");
        jFileLabel10.setFocusable(false);
        jFileLabel10.setRequestFocusEnabled(false);

        jFileLabel11.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jFileLabel11.setForeground(new java.awt.Color(249, 5, 1));
        jFileLabel11.setText("Fields Marked with * are compulsory.");
        jFileLabel11.setFocusable(false);
        jFileLabel11.setRequestFocusEnabled(false);

        jFileLabel12.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jFileLabel12.setForeground(new java.awt.Color(24, 0, 161));
        jFileLabel12.setText("Organisation (O) :");
        jFileLabel12.setFocusable(false);
        jFileLabel12.setRequestFocusEnabled(false);

        jFileLabel13.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jFileLabel13.setForeground(new java.awt.Color(24, 0, 161));
        jFileLabel13.setText("Organisation Unit (OU) :");
        jFileLabel13.setFocusable(false);
        jFileLabel13.setRequestFocusEnabled(false);

        jCountryComboBox.setModel(new javax.swing.DefaultComboBoxModel(getAllCountries()));

        jFileLabel14.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jFileLabel14.setForeground(new java.awt.Color(18, 9, 64));
        jFileLabel14.setText("Other Details: ");
        jFileLabel14.setFocusable(false);
        jFileLabel14.setRequestFocusEnabled(false);

        jInterLabel.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jInterLabel.setForeground(new java.awt.Color(24, 0, 161));
        jInterLabel.setText("Number of intermediate Certificate Authorities in trust hierarchy:*");
        jInterLabel.setFocusable(false);
        jInterLabel.setRequestFocusEnabled(false);

        jFileLabel15.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jFileLabel15.setForeground(new java.awt.Color(24, 0, 161));
        jFileLabel15.setText("Number of days of validity of the certificate:*");
        jFileLabel15.setFocusable(false);
        jFileLabel15.setRequestFocusEnabled(false);

        jFileLabel16.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jFileLabel16.setForeground(new java.awt.Color(24, 0, 161));
        jFileLabel16.setText("Password for verification and future reference:*");
        jFileLabel16.setFocusable(false);
        jFileLabel16.setRequestFocusEnabled(false);

        jFileLabel17.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jFileLabel17.setForeground(new java.awt.Color(24, 0, 161));
        jFileLabel17.setText("Ree-Enter Password :*");
        jFileLabel17.setFocusable(false);
        jFileLabel17.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jSenderTable1Layout = new javax.swing.GroupLayout(jSenderTable1);
        jSenderTable1.setLayout(jSenderTable1Layout);
        jSenderTable1Layout.setHorizontalGroup(
            jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSenderTable1Layout.createSequentialGroup()
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSenderTable1Layout.createSequentialGroup()
                        .addGap(598, 598, 598)
                        .addComponent(jFileLabel9))
                    .addGroup(jSenderTable1Layout.createSequentialGroup()
                        .addGap(568, 568, 568)
                        .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFileLabel11)
                            .addComponent(jFileLabel6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSenderTable1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSenderTable1Layout.createSequentialGroup()
                        .addComponent(jFileLabel14)
                        .addGap(592, 592, 592))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSenderTable1Layout.createSequentialGroup()
                        .addComponent(jRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(472, 472, 472))))
            .addGroup(jSenderTable1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSenderTable1Layout.createSequentialGroup()
                        .addComponent(jFileLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(jSenderTable1Layout.createSequentialGroup()
                        .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jSenderTable1Layout.createSequentialGroup()
                                .addComponent(jFileLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(463, 463, 463)
                                .addComponent(jCountryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jSenderTable1Layout.createSequentialGroup()
                                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFileLabel1)
                                    .addComponent(jFileLabel13)
                                    .addComponent(jFileLabel12)
                                    .addComponent(jFileLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(374, 374, 374)
                                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCityField)
                                    .addComponent(jOField)
                                    .addComponent(jOUField)
                                    .addComponent(jNameField)
                                    .addComponent(jEmailIdField)))
                            .addGroup(jSenderTable1Layout.createSequentialGroup()
                                .addComponent(jFileLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(208, 208, 208)
                                .addComponent(jStateField))
                            .addGroup(jSenderTable1Layout.createSequentialGroup()
                                .addComponent(jInterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField)
                                    .addComponent(jNumberInterCAField)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(182, 182, 182))
                    .addGroup(jSenderTable1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jFileLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(jTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(jSenderTable1Layout.createSequentialGroup()
                        .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFileLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jSenderTable1Layout.createSequentialGroup()
                                .addComponent(jFileLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(jValiditySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jSenderTable1Layout.setVerticalGroup(
            jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSenderTable1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFileLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFileLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmailIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFileLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jOUField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFileLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFileLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFileLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCountryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jFileLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNumberInterCAField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValiditySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSenderTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1915, 1915, 1915)
                .addComponent(jRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Registration", jSenderTable1);

        jFileLabel5.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        jFileLabel5.setForeground(new java.awt.Color(253, 69, 13));
        jFileLabel5.setText("CERTIFICATION AUTHORITY DESK:");
        jFileLabel5.setFocusable(false);
        jFileLabel5.setRequestFocusEnabled(false);

        jIssuerNameArea.setEditable(false);
        jIssuerNameArea.setBackground(new java.awt.Color(248, 241, 186));
        jIssuerNameArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jIssuerNameArea.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jIssuerNameArea.setForeground(new java.awt.Color(127, 40, 14));
        jIssuerNameArea.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jIssuerNameArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jFileLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFileLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1963, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public String[] getAllCountries() {
        String[] countries = new String[Locale.getISOCountries().length];
        String[] countryCodes = Locale.getISOCountries();
        for (int i = 0; i < countryCodes.length; i++) {
            Locale obj = new Locale("", countryCodes[i]);
            countries[i] = obj.getDisplayCountry();
        }
        return countries;
    }
            
    private void jDestinationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDestinationButtonActionPerformed
        if(!jDestinationField.getText().isEmpty()) return;
        JFileChooser filechooser;
        //if(controller.getDestinationFolder().equals(""))
        String filepath=jDestinationField.getText();
        filechooser=new JFileChooser();
        filechooser.removeChoosableFileFilter(filechooser.getAcceptAllFileFilter());
        filechooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File pathname) {
                return pathname.canWrite() && pathname.canExecute();
            }

            @Override
            public String getDescription() {
                return "Executable and writable folders";
            }
        });
        //else filechooser=new JFileChooser(new File(controller.getDestinationFolder()));
        filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        filechooser.setMultiSelectionEnabled(false);
        if(filechooser.showDialog(this,"Choose Folder")==JFileChooser.APPROVE_OPTION)
        {
            if(!filechooser.getSelectedFile().exists())
            { JOptionPane.showMessageDialog(this,"Invalid Folder path", "Error",
                JOptionPane.ERROR_MESSAGE); jDestinationField.setText(filepath);
        }
        else jDestinationField.setText(filechooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_jDestinationButtonActionPerformed

    private void jCAIPfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCAIPfieldFocusLost
        // TODO add your handling code here:
        String ip=jCAIPfield.getText();
        if (ip.isEmpty() ){
            return;
        }
        CAHostName=false;
        int i,num;
        for(i=0;i<ip.length();i++)
        {//to check for other characters
            if(ip.charAt(i)=='/' || Character.isLetterOrDigit(ip.charAt(i)) || ip.charAt(i)=='.' ||ip.charAt(i)==':'|| ip.charAt(i)=='-'); else break;
        }
        if(i!=ip.length())
        {
            JOptionPane.showMessageDialog(this,"Address/Hostname can only contain A_Z,0-9,.,/,-:", "Error",
                JOptionPane.ERROR_MESSAGE);
            jCAIPfield.requestFocus();jCAIPfield.selectAll();return;
        }
        if(ip.endsWith("http://") || ip.endsWith("https://"))
        {
            JOptionPane.showMessageDialog(this,"Incomplete names, Must have something other than protocols", "Error",
                JOptionPane.ERROR_MESSAGE);
            jCAIPfield.requestFocus();jCAIPfield.selectAll();return;
        }
        //to check for ipv4 checking
        StringTokenizer parts = new StringTokenizer(ip, "/.");
        if ( parts.countTokens() > 5 || parts.countTokens()<=2) {
            JOptionPane.showMessageDialog(this,"Considered Hostname", "Information",
                JOptionPane.INFORMATION_MESSAGE);CAHostName=true; return;
        }
        int n=parts.countTokens();
        for ( i=1;i<=n;i++)
        {//to check for hostname or ip
            String s=parts.nextToken().toString();
            try{
                int parseInt = Integer.parseInt( s );
            }
            catch (NumberFormatException nfe) {
                if(s.isEmpty()) {JOptionPane.showMessageDialog(this,"Invalid name or address", "Error",
                    JOptionPane.ERROR_MESSAGE); jCAIPfield.requestFocus();jCAIPfield.selectAll();return;}
            JOptionPane.showMessageDialog(this,"Considered as Hostname", "Information",
                JOptionPane.INFORMATION_MESSAGE); CAHostName=true;  return;
        }
        }
        CAHostName=false;
        parts=new StringTokenizer(ip, ".");
        if(parts.countTokens()!=4 || ip.endsWith(".") || ip.indexOf('/')!=-1)
        {
            JOptionPane.showMessageDialog(this,"Invalid IP Address", "Error",
                JOptionPane.ERROR_MESSAGE);
            jCAIPfield.requestFocus();jCAIPfield.selectAll(); return;
        }

        for ( i=0; i<4;i++)
        {//valid periods
            num = Integer.parseInt( parts.nextToken().toString() );
            if(num<0 || num>255) {JOptionPane.showMessageDialog(this,"Valid IP Address has periods from 0 to 255", "Error",
                JOptionPane.ERROR_MESSAGE);
            jCAIPfield.requestFocus();jCAIPfield.selectAll(); return;
        }
        }
    }//GEN-LAST:event_jCAIPfieldFocusLost

    private void jBufferFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBufferFieldFocusLost

        int buffer;
        try
        {
            buffer=Integer.parseInt(jBufferField.getText());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Buffer Size has to be an integer!!", "Error",
                JOptionPane.ERROR_MESSAGE);
            jBufferField.selectAll();jBufferField.requestFocus(); return;
        }
        if(buffer>1024 || buffer<=0){
            JOptionPane.showMessageDialog(this,"Illegal or too much buffer!", "Error",
                JOptionPane.ERROR_MESSAGE);
            jBufferField.selectAll();jBufferField.requestFocus(); return; }
    }//GEN-LAST:event_jBufferFieldFocusLost

    private void jApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApplyButtonActionPerformed
        if(jDestinationField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Destination Folder not given", "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(jBufferField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Buffer Size not given", "Error",
                JOptionPane.ERROR_MESSAGE);
            jBufferField.selectAll();jBufferField.requestFocus(); return;
        }
        if( jCAIPfield.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Certifying Authority Address required in for verification", "Error",
                JOptionPane.ERROR_MESSAGE);
            jCAIPfield.requestFocus(); return;
        }

        EndUser.setDestiFolder(jDestinationField.getText());
        EndUser.setBufferSize(Integer.parseInt(jBufferField.getText()));
        EndUser.setCAIP(jCAIPfield.getText());
        EndUser.setAlgoType(jAlgoBox.getSelectedIndex()==1?"DES":"AES");
        jChangesSuccessfulLabel.setForeground(Color.RED);
        jChangesSuccessfulLabel.setText("Changes Applied Successfully!!");
        jChangesSuccessfulLabel.setVisible(true);
        new Display(this).start();
    }//GEN-LAST:event_jApplyButtonActionPerformed

    private void jCancelChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelChangesButtonActionPerformed
        jDestinationField.setText(EndUser.getDestiFolder());
        jBufferField.setText(""+EndUser.getBufferSize());
        if(EndUser.getAlgoType().equals("AES"))
        jAlgoBox.setSelectedIndex(0); else   jAlgoBox.setSelectedIndex(1);
        jCAIPfield.setText(EndUser.getCAIP());
    }//GEN-LAST:event_jCancelChangesButtonActionPerformed

    private void jClearChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearChangesButtonActionPerformed
        jChangesSuccessfulLabel.setForeground(Color.red);
        jChangesSuccessfulLabel.setText("Crucial Fields empty! Until applied, old settings would work...");
        jDestinationField.setText("");
        jBufferField.setText(null);
        jCAIPfield.setText(null);
        jAlgoBox.setSelectedIndex(0);
        jChangesSuccessfulLabel.setVisible(true);
        new Display(this).start();
    }//GEN-LAST:event_jClearChangesButtonActionPerformed

    private void jRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButtonActionPerformed
        // TODO add your handling code here:
        SenderSideTransfer record;
        if (jNameField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name Field left empty", "Error",
                JOptionPane.ERROR_MESSAGE);
            jNameField.requestFocus();
            return;
        }
        if (jEmailIdField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email Id not mentioned", "Error",
                JOptionPane.ERROR_MESSAGE);
            jEmailIdField.requestFocus();
            return;
        }
        else{
            Pattern VALID_EMAIL_ADDRESS_REGEX =
            Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
            Matcher matcher = VALID_EMAIL_ADDRESS_REGEX.matcher(jEmailIdField.getText().toString());
            if(!matcher.find())
            {
                JOptionPane.showMessageDialog(this, "Invalid Email Id", "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            jEmailIdField.requestFocus();
        }

        if (jStateField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "State Field left Empty", "Error",
                JOptionPane.ERROR_MESSAGE);
            jStateField.requestFocus();
            return;
        }
        if (jCityField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "City Field left Empty", "Error",
                JOptionPane.ERROR_MESSAGE);
            jCityField.requestFocus();
            return;
        }

        if (jPasswordField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password Field left Empty", "Error",
                JOptionPane.ERROR_MESSAGE);
            jPasswordField.requestFocus();
            return;
        }
        if (jPublicKeyField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Public Key Field left Empty", "Error",
                JOptionPane.ERROR_MESSAGE);
            jPublicKeyField.requestFocus();
            return;
        }
    }//GEN-LAST:event_jRegisterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CertifyingAuthorityInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CertifyingAuthorityInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CertifyingAuthorityInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CertifyingAuthorityInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CertifyingAuthorityInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jAlgoBox;
    private javax.swing.JButton jApplyButton;
    private javax.swing.JTextField jBufferField;
    private javax.swing.JLabel jCAIPLabel;
    private javax.swing.JTextField jCAIPfield;
    private javax.swing.JTextField jCANameField;
    private javax.swing.JButton jCancelChangesButton;
    private javax.swing.JLabel jChangesSuccessfulLabel;
    private javax.swing.JTextField jCityField;
    private javax.swing.JButton jClearChangesButton;
    private javax.swing.JLabel jConnectionsLabel6;
    private javax.swing.JLabel jConnectionsLabel7;
    private javax.swing.JLabel jConnectionsLabel9;
    private javax.swing.JComboBox jCountryComboBox;
    private javax.swing.JButton jDestinationButton;
    private javax.swing.JTextField jDestinationField;
    private javax.swing.JLabel jDestinationLabel;
    private javax.swing.JTextField jEmailIdField;
    private javax.swing.JLabel jFileLabel;
    private javax.swing.JLabel jFileLabel1;
    private javax.swing.JLabel jFileLabel10;
    private javax.swing.JLabel jFileLabel11;
    private javax.swing.JLabel jFileLabel12;
    private javax.swing.JLabel jFileLabel13;
    private javax.swing.JLabel jFileLabel14;
    private javax.swing.JLabel jFileLabel15;
    private javax.swing.JLabel jFileLabel16;
    private javax.swing.JLabel jFileLabel17;
    private javax.swing.JLabel jFileLabel2;
    private javax.swing.JLabel jFileLabel3;
    private javax.swing.JLabel jFileLabel4;
    private javax.swing.JLabel jFileLabel5;
    private javax.swing.JLabel jFileLabel6;
    private javax.swing.JLabel jFileLabel9;
    private javax.swing.JLabel jInterLabel;
    private javax.swing.JTextPane jIssuerNameArea;
    private javax.swing.JTextField jMyUNameField;
    private javax.swing.JTextField jNameField;
    private javax.swing.JTextField jNumberInterCAField;
    private javax.swing.JTextField jOField;
    private javax.swing.JTextField jOUField;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel jProxyLabel5;
    private javax.swing.JButton jRegisterButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jSenderTable1;
    private javax.swing.JPanel jSettings;
    private javax.swing.JTextField jStateField;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTypeField;
    private javax.swing.JLabel jUserName;
    private javax.swing.JLabel jUserName1;
    private javax.swing.JSpinner jValiditySpinner;
    // End of variables declaration//GEN-END:variables
}
