/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Splash.java
 *
 * Created on Sep 21, 2014, 6:42:18 PM
 */
package publickeyinfrastructure;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import sun.security.x509.X500Name;

  
/**
 *
 * @author Dell
 */
public class Splash extends javax.swing.JFrame {
     

    /** Creates new form Startup */
    public Splash() {
        initComponents();
        Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
        int jFrameh=this.getSize().height;
        int jFramew=this.getSize().width;
        setLocation((dim.width-jFramew)/2,(dim.height-jFrameh)/2);  
        progressBar.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        progressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jExitButton = new javax.swing.JButton();
        MoveDashButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(-11400070,true));
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(-16776961,true));

        jPanel3.setBackground(new java.awt.Color(-20561,true));

        jTextField1.setBackground(new java.awt.Color(-1,true));
        jTextField1.setFont(new java.awt.Font("Serif", 1, 24));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Public Key Infrastructure");
        jTextField1.setToolTipText("");
        jTextField1.setFocusable(false);

        progressBar.setForeground(new java.awt.Color(-16711936,true));
        progressBar.setFocusable(false);
        progressBar.setRequestFocusEnabled(false);
        progressBar.setStringPainted(true);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 50, 0));
        jLabel1.setText("Team- The Cryptifiers");
        jLabel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLayeredPane1.add(jPanel3);
        jPanel3.setBounds(40, 10, 380, 230);

        jExitButton.setBackground(new java.awt.Color(-256,true));
        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jExitButton);
        jExitButton.setBounds(20, 290, 80, 29);

        MoveDashButton.setBackground(new java.awt.Color(255, 255, 175));
        MoveDashButton.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        MoveDashButton.setText("Move to Dashboard>>");
        MoveDashButton.setActionCommand("DashMove");
        MoveDashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveDashButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(MoveDashButton);
        MoveDashButton.setBounds(170, 270, 270, 60);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
System.exit(0);
}//GEN-LAST:event_jExitButtonActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
timer=new Timer(20, new progress1(this));
}//GEN-LAST:event_formWindowOpened

    private void MoveDashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveDashButtonActionPerformed
        // TODO add your handling code here:
         progressBar.setValue(0);
        progressBar.setVisible(true);
        timer.start();
    }//GEN-LAST:event_MoveDashButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                
            }
        });
    }
    
    public class progress1 implements ActionListener
    {
        Splash k;
        progress1(Splash s1)
        {
            k=s1;
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            int j=progressBar.getValue();
            if(j<100)
            {
                j++; progressBar.setValue(j);
            }
            else 
            {
                
                  timer.stop();
                  X500Name m;
                 if(SettingsStorageDatabase.seek((byte)0).isEmpty()) {
                         String options[]={"End Users(Need to register with the CA)","Certifying Authority(register, validate and issue certificates)"}; 
                         String CAoptions[]={"Root CA(Highest trust Authority)","Intermediate CA(vouch for sub-ordinate CAs)","End Chain CA(vouch for End Users)"}; 
                         int ch=-1,ch2=-1;
                         while(ch!=0 && ch!=1)
                         {
                             ch= JOptionPane.showOptionDialog(k, "Seems you have installed for the first time!! Select one of the following system configuration", "Select System Configuration",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null, options, options[0]);
 
                         switch(ch)
                        {
                        case 0:SettingsStorageDatabase.update((byte)0, "End User"); break;
                            case 1:
                                while(ch2<0 || ch2>2)
                                {
                                ch2= JOptionPane.showOptionDialog(k, "Now that you are a CA, Select the type of CA you wish to be!!", "Select CA Type",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null, CAoptions, CAoptions[0]);
                                    switch(ch2)
                                    {
                                    case 0: SettingsStorageDatabase.update((byte)0, "CA-R"); break;
                                    case 1:SettingsStorageDatabase.update((byte)0, "CA-I"); break;
                                    case 2: SettingsStorageDatabase.update((byte)0, "CA-E"); break;
                                    default:JOptionPane.showMessageDialog(k, "Compulsory to choose one system", "Error Message", JOptionPane.ERROR_MESSAGE);
                                    }
                                }
                                break;
                            default:JOptionPane.showMessageDialog(k, "Compulsory to choose one system", "Error Message", JOptionPane.ERROR_MESSAGE);
                        }
                         }
                   }
                try {
                     m=new X500Name("C=India,L=Birhana Road,CN=Somil Gupta,EMAIL=somiltgupta@gmail.com,O=Motilal Nehru National Institute Of Technology,OU=Information Technology");
                     //System.err.println(m);
                    new CertifyingAuthorityInterface(m).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                }
                     k.setVisible(false);
                
                progressBar.setVisible(false);
            }
        }
    }
      private Timer timer;
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MoveDashButton;
    private javax.swing.JButton jExitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
 
}